print("Work 3")
A = float(input("Enter number a: "))
B = float(input("Enter number b: "))
Height = float(input("Enter number of height: "))
ParalellSize = A + B
Area = float(0.5 * ParalellSize * Height)
print("Paralell size is: {0}".format(ParalellSize))
print("Height is: {0}".format(Height))
print("Area is: {0}".format(Area))
print("Nameใส่ชื่อตัวเอเง")
